"""create bahnhof table

Revision ID: 049d84d15cc8
Revises: 410528306669
Create Date: 2025-11-12 11:14:57.400354

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '049d84d15cc8'
down_revision = '410528306669'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('bahnhof',
    sa.Column('bahnhofId', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=False),
    sa.Column('adresse', sa.String(length=120), nullable=False),
    sa.Column('latitude', sa.Float(), nullable=True),
    sa.Column('longitude', sa.Float(), nullable=True),
    sa.PrimaryKeyConstraint('bahnhofId')
    )
    with op.batch_alter_table('bahnhof', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_bahnhof_adresse'), ['adresse'], unique=True)
        batch_op.create_index(batch_op.f('ix_bahnhof_name'), ['name'], unique=True)

    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.alter_column('role',
               existing_type=sa.TEXT(),
               type_=sa.Enum('admin', 'mitarbeiter', name='roleenum'),
               nullable=False,
               existing_server_default=sa.text("'mitarbeiter'"))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.alter_column('role',
               existing_type=sa.Enum('admin', 'mitarbeiter', name='roleenum'),
               type_=sa.TEXT(),
               nullable=True,
               existing_server_default=sa.text("'mitarbeiter'"))

    with op.batch_alter_table('bahnhof', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_bahnhof_name'))
        batch_op.drop_index(batch_op.f('ix_bahnhof_adresse'))

    op.drop_table('bahnhof')
    # ### end Alembic commands ###
