"""warnungen abschnitte

Revision ID: 0bc4504ce779
Revises: f42ffa30a153
Create Date: 2025-11-20 16:37:27.507367

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0bc4504ce779'
down_revision = 'f42ffa30a153'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('warnung',
    sa.Column('warnungId', sa.Integer(), nullable=False),
    sa.Column('bezeichnung', sa.String(length=100), nullable=False),
    sa.Column('beschreibung', sa.Text(), nullable=True),
    sa.Column('startZeit', sa.DateTime(), nullable=False),
    sa.Column('endZeit', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('warnungId')
    )
    op.create_table('abschnitt_warnung',
    sa.Column('abschnitt_id', sa.Integer(), nullable=False),
    sa.Column('warnung_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['abschnitt_id'], ['abschnitt.abschnittId'], ),
    sa.ForeignKeyConstraint(['warnung_id'], ['warnung.warnungId'], ),
    sa.PrimaryKeyConstraint('abschnitt_id', 'warnung_id')
    )
    with op.batch_alter_table('abschnitt', schema=None) as batch_op:
        batch_op.add_column(sa.Column('startBahnhofId', sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column('endBahnhofId', sa.Integer(), nullable=False))
        batch_op.drop_index(batch_op.f('ix_abschnitt_endBahnhof'))
        batch_op.drop_index(batch_op.f('ix_abschnitt_startBahnhof'))
        batch_op.create_index(batch_op.f('ix_abschnitt_endBahnhofId'), ['endBahnhofId'], unique=False)
        batch_op.create_index(batch_op.f('ix_abschnitt_startBahnhofId'), ['startBahnhofId'], unique=False)
        batch_op.create_foreign_key(None, 'bahnhof', ['startBahnhofId'], ['bahnhofId'])
        batch_op.create_foreign_key(None, 'bahnhof', ['endBahnhofId'], ['bahnhofId'])
        batch_op.drop_column('endBahnhof')
        batch_op.drop_column('startBahnhof')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('abschnitt', schema=None) as batch_op:
        batch_op.add_column(sa.Column('startBahnhof', sa.INTEGER(), nullable=False))
        batch_op.add_column(sa.Column('endBahnhof', sa.INTEGER(), nullable=False))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(None, 'bahnhof', ['startBahnhof'], ['bahnhofId'])
        batch_op.create_foreign_key(None, 'bahnhof', ['endBahnhof'], ['bahnhofId'])
        batch_op.drop_index(batch_op.f('ix_abschnitt_startBahnhofId'))
        batch_op.drop_index(batch_op.f('ix_abschnitt_endBahnhofId'))
        batch_op.create_index(batch_op.f('ix_abschnitt_startBahnhof'), ['startBahnhof'], unique=False)
        batch_op.create_index(batch_op.f('ix_abschnitt_endBahnhof'), ['endBahnhof'], unique=False)
        batch_op.drop_column('endBahnhofId')
        batch_op.drop_column('startBahnhofId')

    op.drop_table('abschnitt_warnung')
    op.drop_table('warnung')
    # ### end Alembic commands ###
