"""strecken

Revision ID: 443477b4a876
Revises: 489c1ee4256b
Create Date: 2025-11-27 10:53:15.197285

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '443477b4a876'
down_revision = '489c1ee4256b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('strecken',
    sa.Column('streckenId', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('streckenId'),
    sa.UniqueConstraint('name')
    )
    op.create_table('strecke_abschnitt',
    sa.Column('streckeId', sa.Integer(), nullable=False),
    sa.Column('abschnittId', sa.Integer(), nullable=False),
    sa.Column('reihenfolge', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['abschnittId'], ['abschnitt.abschnittId'], ),
    sa.ForeignKeyConstraint(['streckeId'], ['strecken.streckenId'], ),
    sa.PrimaryKeyConstraint('streckeId', 'abschnittId'),
    sa.UniqueConstraint('streckeId', 'reihenfolge', name='_strecke_reihenfolge_uc')
    )
    with op.batch_alter_table('abschnitt', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_abschnitt_endBahnhofId'), ['endBahnhofId'], unique=False)
        batch_op.create_index(batch_op.f('ix_abschnitt_startBahnhofId'), ['startBahnhofId'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('abschnitt', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_abschnitt_startBahnhofId'))
        batch_op.drop_index(batch_op.f('ix_abschnitt_endBahnhofId'))

    op.drop_table('strecke_abschnitt')
    op.drop_table('strecken')
    # ### end Alembic commands ###
