"""Laenge hinzugefuegt

Revision ID: 6c59bce87f77
Revises: 87354d4793ed
Create Date: 2025-12-15 19:32:41.190336

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6c59bce87f77'
down_revision = '87354d4793ed'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('abschnitt', schema=None) as batch_op:
        batch_op.add_column(sa.Column('laenge', sa.Float(), nullable=False,server_default="0"))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('abschnitt', schema=None) as batch_op:
        batch_op.drop_column('laenge')

    # ### end Alembic commands ###
