"""empty message

Revision ID: 87354d4793ed
Revises: 443477b4a876
Create Date: 2025-11-27 12:15:10.291040

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '87354d4793ed'
down_revision = '443477b4a876'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('strecken', schema=None) as batch_op:
        batch_op.drop_column('startBahnhofId')
        batch_op.drop_column('endBahnhofId')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('strecken', schema=None) as batch_op:
        batch_op.add_column(sa.Column('endBahnhofId', sa.INTEGER(), nullable=True))
        batch_op.add_column(sa.Column('startBahnhofId', sa.INTEGER(), nullable=True))

    # ### end Alembic commands ###
