"""Abschnitt table

Revision ID: f42ffa30a153
Revises: 049d84d15cc8
Create Date: 2025-11-19 18:30:18.485267

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f42ffa30a153'
down_revision = '049d84d15cc8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('abschnitt',
    sa.Column('abschnittId', sa.Integer(), nullable=False),
    sa.Column('spurweite', sa.Float(), nullable=False),
    sa.Column('nutzungsentgelt', sa.Float(), nullable=False),
    sa.Column('max_geschwindigkeit', sa.Integer(), nullable=False),
    sa.Column('startBahnhof', sa.Integer(), nullable=False),
    sa.Column('endBahnhof', sa.Integer(), nullable=False),
    sa.CheckConstraint('startBahnhof <> endBahnhof', name='check_start_end_ungleich'),
    sa.ForeignKeyConstraint(['endBahnhof'], ['bahnhof.bahnhofId'], ),
    sa.ForeignKeyConstraint(['startBahnhof'], ['bahnhof.bahnhofId'], ),
    sa.PrimaryKeyConstraint('abschnittId')
    )
    with op.batch_alter_table('abschnitt', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_abschnitt_endBahnhof'), ['endBahnhof'], unique=False)
        batch_op.create_index(batch_op.f('ix_abschnitt_startBahnhof'), ['startBahnhof'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('abschnitt', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_abschnitt_startBahnhof'))
        batch_op.drop_index(batch_op.f('ix_abschnitt_endBahnhof'))

    op.drop_table('abschnitt')
    # ### end Alembic commands ###
