"""Unique Constraint entfernt bei Wartungszeitraum

Revision ID: 121b44b1ce61
Revises: 6c1b540394ca
Create Date: 2026-01-16 18:25:07.089075

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '121b44b1ce61'
down_revision = '6c1b540394ca'
branch_labels = None
depends_on = None


def upgrade():
    # Foreign Key Constraints für SQLite deaktivieren
    if op.get_context().dialect.name == 'sqlite':
        op.execute('PRAGMA foreign_keys=OFF')

    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('wartungszeitraum', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('unique_datum_von_bis'), type_='unique')

    # Foreign Key Constraints wieder aktivieren
    if op.get_context().dialect.name == 'sqlite':
        op.execute('PRAGMA foreign_keys=ON')

    # ### end Alembic commands ###


def downgrade():
    # Foreign Key Constraints für SQLite deaktivieren
    if op.get_context().dialect.name == 'sqlite':
        op.execute('PRAGMA foreign_keys=OFF')

    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('wartungszeitraum', schema=None) as batch_op:
        batch_op.create_unique_constraint(batch_op.f('unique_datum_von_bis'), ['datum', 'von', 'bis'])

    # Foreign Key Constraints wieder aktivieren
    if op.get_context().dialect.name == 'sqlite':
        op.execute('PRAGMA foreign_keys=ON')
    # ### end Alembic commands ###
