"""Wartungszeitraum + Wartung ternäre Beziehung hinzugefügt

Revision ID: 13f042e2d656
Revises: 3b39a15bf95e
Create Date: 2025-11-30 16:39:12.365049

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '13f042e2d656'
down_revision = '3b39a15bf95e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('wartungszeitraum',
    sa.Column('wartungszeitid', sa.Integer(), nullable=False),
    sa.Column('datum', sa.Date(), nullable=False),
    sa.Column('von', sa.DateTime(), nullable=False),
    sa.Column('bis', sa.DateTime(), nullable=False),
    sa.Column('dauer', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('wartungszeitid')
    )
    with op.batch_alter_table('wartungszeitraum', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_wartungszeitraum_datum'), ['datum'], unique=False)

    op.create_table('wartung',
    sa.Column('wartungid', sa.Integer(), nullable=False),
    sa.Column('svnr', sa.Integer(), nullable=False),
    sa.Column('zugid', sa.Integer(), nullable=False),
    sa.Column('wartungszeitid', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['svnr'], ['mitarbeiter.svnr'], ),
    sa.ForeignKeyConstraint(['wartungszeitid'], ['wartungszeitraum.wartungszeitid'], ),
    sa.ForeignKeyConstraint(['zugid'], ['zuege.zugid'], ),
    sa.PrimaryKeyConstraint('wartungid')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('wartung')
    with op.batch_alter_table('wartungszeitraum', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_wartungszeitraum_datum'))

    op.drop_table('wartungszeitraum')
    # ### end Alembic commands ###
