"""Mitarbeiter Table hinzugefügt

Revision ID: 3b39a15bf95e
Revises: 804793fdf819
Create Date: 2025-11-27 15:29:12.878478

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3b39a15bf95e'
down_revision = '804793fdf819'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('mitarbeiter',
    sa.Column('svnr', sa.Integer(), nullable=False),
    sa.Column('vorname', sa.String(length=64), nullable=False),
    sa.Column('nachname', sa.String(length=64), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('svnr'),
    sa.UniqueConstraint('user_id')
    )
    with op.batch_alter_table('mitarbeiter', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_mitarbeiter_nachname'), ['nachname'], unique=False)
        batch_op.create_index(batch_op.f('ix_mitarbeiter_vorname'), ['vorname'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('mitarbeiter', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_mitarbeiter_vorname'))
        batch_op.drop_index(batch_op.f('ix_mitarbeiter_nachname'))

    op.drop_table('mitarbeiter')
    # ### end Alembic commands ###
