"""Unique Constraint fix

Revision ID: 46b4f4d6cf02
Revises: 5a9253fc12b5
Create Date: 2025-12-03 19:02:50.702570

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '46b4f4d6cf02'
down_revision = '5a9253fc12b5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("PRAGMA foreign_keys = OFF;")

    op.drop_table('_alembic_tmp_wartungszeitraum')
    with op.batch_alter_table('wartungszeitraum', schema=None) as batch_op:
        batch_op.create_unique_constraint('unique_datum_von_bis', ['datum', 'von', 'bis'])

    op.execute("PRAGMA foreign_keys = ON;")
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###

    op.execute("PRAGMA foreign_keys = OFF;")

    with op.batch_alter_table('wartungszeitraum', schema=None) as batch_op:
        batch_op.drop_constraint('unique_datum_von_bis', type_='unique')

    op.create_table('_alembic_tmp_wartungszeitraum',
    sa.Column('wartungszeitid', sa.INTEGER(), nullable=False),
    sa.Column('datum', sa.DATE(), nullable=False),
    sa.Column('von', sa.DATETIME(), nullable=False),
    sa.Column('bis', sa.DATETIME(), nullable=False),
    sa.Column('dauer', sa.INTEGER(), nullable=False),
    sa.PrimaryKeyConstraint('wartungszeitid'),
    sa.UniqueConstraint('datum', 'von', 'bis', name=op.f('unique_datum_von_bis'))
    )

    op.execute("PRAGMA foreign_keys = ON;")
    # ### end Alembic commands ###
