""" inwartung Feld aus Zuege entfernt

Revision ID: 5a9253fc12b5
Revises: 13f042e2d656
Create Date: 2025-12-01 16:29:53.951364

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5a9253fc12b5'
down_revision = '13f042e2d656'
branch_labels = None
depends_on = None


def upgrade():
    op.execute("PRAGMA foreign_keys=OFF;")

    op.execute("DROP TABLE IF EXISTS _alembic_tmp_zuege;")
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('zuege', schema=None) as batch_op:
        batch_op.drop_column('inwartung')

    # ### end Alembic commands ###
    op.execute("PRAGMA foreign_keys=ON;")


def downgrade():
    op.execute("PRAGMA foreign_keys=OFF;")
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('zuege', schema=None) as batch_op:
        batch_op.add_column(sa.Column('inwartung', sa.BOOLEAN(), nullable=False, server_default=sa.text('0')))

    # ### end Alembic commands ###
    op.execute("PRAGMA foreign_keys=ON;")
