"""wartungen mitarbeiter cascade fix

Revision ID: 6c1b540394ca
Revises: 46b4f4d6cf02
Create Date: 2025-12-18 17:11:41.004332

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6c1b540394ca'
down_revision = '46b4f4d6cf02'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('wartung', schema=None) as batch_op:
       # batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('wartung cascade fix', 'mitarbeiter', ['svnr'], ['svnr'], ondelete='cascade')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('wartung', schema=None) as batch_op:
     #   batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('wartung cascade fix', 'mitarbeiter', ['svnr'], ['svnr'])

    # ### end Alembic commands ###
