"""Zuege hinzugefuegt

Revision ID: 804793fdf819
Revises: 905aefe6d5dc
Create Date: 2025-11-21 16:45:09.970445

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '804793fdf819'
down_revision = '905aefe6d5dc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute('PRAGMA foreign_keys=OFF')
    op.execute('DROP TABLE IF EXISTS _alembic_tmp_wagen')
    with op.batch_alter_table('wagen', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_wagen_istfrei'), ['istfrei'], unique=False)
        batch_op.create_index(batch_op.f('ix_wagen_spurweite'), ['spurweite'], unique=False)
        batch_op.create_foreign_key('fk_wagen_zug_id', 'zuege', ['istfrei'], ['zugid'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute('PRAGMA foreign_keys=OFF')
    with op.batch_alter_table('wagen', schema=None) as batch_op:
        batch_op.drop_constraint('fk_wagen_zug_id', type_='foreignkey')
        batch_op.drop_index(batch_op.f('ix_wagen_spurweite'))
        batch_op.drop_index(batch_op.f('ix_wagen_istfrei'))

    op.create_table('_alembic_tmp_wagen',
    sa.Column('wagenid', sa.INTEGER(), nullable=False),
    sa.Column('spurweite', sa.FLOAT(), nullable=False),
    sa.Column('istfrei', sa.INTEGER(), nullable=True),
    sa.Column('type', sa.VARCHAR(length=50), nullable=False),
    sa.ForeignKeyConstraint(['istfrei'], ['zuege.zugid'], name=op.f('fk_wagen_zugid')),
    sa.PrimaryKeyConstraint('wagenid')
    )
    # ### end Alembic commands ###
