"""Wagen vererbung + Personen- und Triebwagen hinzugefügt

Revision ID: 905aefe6d5dc
Revises: 06e9b19e14f0
Create Date: 2025-11-14 15:51:12.567910

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '905aefe6d5dc'
down_revision = '06e9b19e14f0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('wagen',
    sa.Column('wagenid', sa.Integer(), nullable=False),
    sa.Column('spurweite', sa.Float(), nullable=False),
    sa.Column('istfrei', sa.Integer(), nullable=True),
    sa.Column('type', sa.String(length=50), nullable=False),
    sa.PrimaryKeyConstraint('wagenid')
    )
    op.create_table('personenwagen',
    sa.Column('personenwagenid', sa.Integer(), nullable=False),
    sa.Column('kapazitaet', sa.Integer(), nullable=False),
    sa.Column('maxgewicht', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['personenwagenid'], ['wagen.wagenid'], ),
    sa.PrimaryKeyConstraint('personenwagenid')
    )
    op.create_table('triebwagen',
    sa.Column('triebwagenid', sa.Integer(), nullable=False),
    sa.Column('maxzugkraft', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['triebwagenid'], ['wagen.wagenid'], ),
    sa.PrimaryKeyConstraint('triebwagenid')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('triebwagen')
    op.drop_table('personenwagen')
    op.drop_table('wagen')
    # ### end Alembic commands ###
