"""ticket-modell

Revision ID: 4dc56523629e
Revises: 0e2ce24ba8fd
Create Date: 2025-12-18 16:56:56.634215

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4dc56523629e'
down_revision = '0e2ce24ba8fd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ticket',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('erstelltAm', sa.DateTime(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('start_halt', sa.String(length=120), nullable=False),
    sa.Column('ziel_halt', sa.String(length=120), nullable=False),
    sa.Column('anzahl_umstiege', sa.Integer(), nullable=False),
    sa.Column('fahrt_id', sa.Integer(), nullable=False),
    sa.Column('halteplan_id', sa.Integer(), nullable=True),
    sa.Column('gesamtPreis', sa.Float(), nullable=False),
    sa.Column('sitzplatzReservierung', sa.Boolean(), nullable=False),
    sa.Column('aktion_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['aktion_id'], ['aktion.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('ticket')
    # ### end Alembic commands ###
