"""schema aligned (named constraints)

Revision ID: 0a4f2c026d15
Revises: 4f5952da6ec4
Create Date: 2026-01-07 21:24:30.503412

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0a4f2c026d15'
down_revision = '4f5952da6ec4'
branch_labels = None
depends_on = None


def upgrade():
    # --- SQLite safety: falls ein früherer Versuch abgebrochen ist ---
    op.execute("PRAGMA foreign_keys=OFF;")
    op.execute("DROP TABLE IF EXISTS _alembic_tmp_abschnitt;")
    # optional (falls du mal andere _alembic_tmp_* Leichen hast):
    # op.execute("DROP TABLE IF EXISTS _alembic_tmp_bahnhof;")

    try:
        # ### commands auto generated by Alembic - please adjust! ###
        with op.batch_alter_table('abschnitt', schema=None) as batch_op:
            batch_op.create_unique_constraint(batch_op.f('uq_abschnitt_external_id'), ['external_id'])

        with op.batch_alter_table('bahnhof', schema=None) as batch_op:
            batch_op.create_unique_constraint(batch_op.f('uq_bahnhof_external_id'), ['external_id'])

        with op.batch_alter_table('dienstzuweisung', schema=None) as batch_op:
            batch_op.drop_constraint(batch_op.f('fk_dienstzuweisung_mitarbeiter'), type_='foreignkey')
            batch_op.create_foreign_key(
                batch_op.f('fk_dienstzuweisung_mitarbeiter_id_mitarbeiter'),
                'mitarbeiter', ['mitarbeiter_id'], ['id']
            )

        with op.batch_alter_table('fahrt_halt', schema=None) as batch_op:
            batch_op.create_index(batch_op.f('ix_fahrt_halt_bahnhof_id'), ['bahnhof_id'], unique=False)
            batch_op.create_index(batch_op.f('ix_fahrt_halt_fahrt_id'), ['fahrt_id'], unique=False)
            batch_op.drop_constraint(batch_op.f('fk_fahrt_halt_bahnhof'), type_='foreignkey')
            batch_op.create_foreign_key(
                batch_op.f('fk_fahrt_halt_bahnhof_id_bahnhof'),
                'bahnhof', ['bahnhof_id'], ['id']
            )

        with op.batch_alter_table('fahrt_segment', schema=None) as batch_op:
            batch_op.create_index(batch_op.f('ix_fahrt_segment_fahrt_id'), ['fahrt_id'], unique=False)
            batch_op.drop_constraint(batch_op.f('fk_fahrt_segment_von_halt'), type_='foreignkey')
            batch_op.drop_constraint(batch_op.f('fk_fahrt_segment_nach_halt'), type_='foreignkey')
            batch_op.create_foreign_key(
                batch_op.f('fk_fahrt_segment_von_halt_id_fahrt_halt'),
                'fahrt_halt', ['von_halt_id'], ['id']
            )
            batch_op.create_foreign_key(
                batch_op.f('fk_fahrt_segment_nach_halt_id_fahrt_halt'),
                'fahrt_halt', ['nach_halt_id'], ['id']
            )

        with op.batch_alter_table('mitarbeiter', schema=None) as batch_op:
            batch_op.create_unique_constraint(batch_op.f('uq_mitarbeiter_user_id'), ['user_id'])

        with op.batch_alter_table('strecke', schema=None) as batch_op:
            batch_op.create_unique_constraint(batch_op.f('uq_strecke_external_id'), ['external_id'])
        # ### end Alembic commands ###

    finally:
        op.execute("PRAGMA foreign_keys=ON;")


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('strecke', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('uq_strecke_external_id'), type_='unique')

    with op.batch_alter_table('mitarbeiter', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('uq_mitarbeiter_user_id'), type_='unique')

    with op.batch_alter_table('fahrt_segment', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_fahrt_segment_nach_halt_id_fahrt_halt'), type_='foreignkey')
        batch_op.drop_constraint(batch_op.f('fk_fahrt_segment_von_halt_id_fahrt_halt'), type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('fk_fahrt_segment_nach_halt'), 'fahrt_halt', ['nach_halt_id'], ['id'], ondelete='CASCADE')
        batch_op.create_foreign_key(batch_op.f('fk_fahrt_segment_von_halt'), 'fahrt_halt', ['von_halt_id'], ['id'], ondelete='CASCADE')
        batch_op.drop_index(batch_op.f('ix_fahrt_segment_fahrt_id'))

    with op.batch_alter_table('fahrt_halt', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_fahrt_halt_bahnhof_id_bahnhof'), type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('fk_fahrt_halt_bahnhof'), 'bahnhof', ['bahnhof_id'], ['id'], ondelete='RESTRICT')
        batch_op.drop_index(batch_op.f('ix_fahrt_halt_fahrt_id'))
        batch_op.drop_index(batch_op.f('ix_fahrt_halt_bahnhof_id'))

    with op.batch_alter_table('dienstzuweisung', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_dienstzuweisung_mitarbeiter_id_mitarbeiter'), type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('fk_dienstzuweisung_mitarbeiter'), 'mitarbeiter', ['mitarbeiter_id'], ['id'], ondelete='CASCADE')

    with op.batch_alter_table('bahnhof', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('uq_bahnhof_external_id'), type_='unique')

    with op.batch_alter_table('abschnitt', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('uq_abschnitt_external_id'), type_='unique')

    # ### end Alembic commands ###
