"""external strecken data added

Revision ID: 2488b374e197
Revises: cd8c44890353
Create Date: 2025-12-16 21:14:11.139194

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2488b374e197'
down_revision = 'cd8c44890353'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('bahnhof',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('external_id', sa.Integer(), nullable=True),
    sa.Column('name', sa.String(length=100), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('external_id')
    )
    op.create_table('strecke',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('external_id', sa.Integer(), nullable=True),
    sa.Column('name', sa.String(length=100), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('external_id')
    )
    op.create_table('abschnitt',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('external_id', sa.Integer(), nullable=True),
    sa.Column('spurweite', sa.Float(), nullable=True),
    sa.Column('max_geschwindigkeit', sa.Integer(), nullable=True),
    sa.Column('nutzungsentgelt', sa.Float(), nullable=True),
    sa.Column('start_bahnhof_id', sa.Integer(), nullable=True),
    sa.Column('end_bahnhof_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['end_bahnhof_id'], ['bahnhof.id'], ),
    sa.ForeignKeyConstraint(['start_bahnhof_id'], ['bahnhof.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('external_id')
    )
    op.create_table('strecke_abschnitt',
    sa.Column('strecke_id', sa.Integer(), nullable=False),
    sa.Column('abschnitt_id', sa.Integer(), nullable=False),
    sa.Column('position', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['abschnitt_id'], ['abschnitt.id'], ),
    sa.ForeignKeyConstraint(['strecke_id'], ['strecke.id'], ),
    sa.PrimaryKeyConstraint('strecke_id', 'abschnitt_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('strecke_abschnitt')
    op.drop_table('abschnitt')
    op.drop_table('strecke')
    op.drop_table('bahnhof')
    # ### end Alembic commands ###
