"""haltedauer added to haltepunkt

Revision ID: 491fc61ff84b
Revises: ab95c3471da3
Create Date: 2025-12-17 22:55:39.304640

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '491fc61ff84b'
down_revision = 'ab95c3471da3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('haltepunkt', schema=None) as batch_op:
        batch_op.add_column(sa.Column('halte_dauer_min', sa.Integer(), server_default='0', nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('haltepunkt', schema=None) as batch_op:
        batch_op.drop_column('halte_dauer_min')

    # ### end Alembic commands ###
