"""halteplan tables added

Revision ID: 5064cbb6c2b4
Revises: 2488b374e197
Create Date: 2025-12-16 22:21:00.396773

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5064cbb6c2b4'
down_revision = '2488b374e197'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('haltepunkt',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('halteplan_id', sa.Integer(), nullable=False),
    sa.Column('bahnhof_id', sa.Integer(), nullable=False),
    sa.Column('position', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['bahnhof_id'], ['bahnhof.id'], ),
    sa.ForeignKeyConstraint(['halteplan_id'], ['halteplan.halteplan_id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('halteplan_id', 'position', name='uq_haltepunkt_pos')
    )
    with op.batch_alter_table('haltepunkt', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_haltepunkt_bahnhof_id'), ['bahnhof_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_haltepunkt_halteplan_id'), ['halteplan_id'], unique=False)

    op.create_table('fahrt_halt',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('fahrt_id', sa.Integer(), nullable=False),
    sa.Column('bahnhof_id', sa.Integer(), nullable=False),
    sa.Column('position', sa.Integer(), nullable=False),
    sa.Column('ankunft_zeit', sa.DateTime(), nullable=True),
    sa.Column('abfahrt_zeit', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['bahnhof_id'], ['bahnhof.id'], ),
    sa.ForeignKeyConstraint(['fahrt_id'], ['fahrtdurchfuehrung.fahrt_id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('fahrt_id', 'position', name='uq_fahrt_halt_pos')
    )
    with op.batch_alter_table('fahrt_halt', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_fahrt_halt_bahnhof_id'), ['bahnhof_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_fahrt_halt_fahrt_id'), ['fahrt_id'], unique=False)

    op.create_table('halteplan_segment',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('halteplan_id', sa.Integer(), nullable=False),
    sa.Column('von_haltepunkt_id', sa.Integer(), nullable=False),
    sa.Column('nach_haltepunkt_id', sa.Integer(), nullable=False),
    sa.Column('position', sa.Integer(), nullable=False),
    sa.Column('base_price', sa.Float(), nullable=False),
    sa.Column('duration_min', sa.Integer(), nullable=False),
    sa.Column('min_cost', sa.Float(), nullable=False),
    sa.CheckConstraint('base_price >= 0', name='ck_hpseg_base_price_nonneg'),
    sa.CheckConstraint('duration_min >= 0', name='ck_hpseg_duration_nonneg'),
    sa.CheckConstraint('min_cost >= 0', name='ck_hpseg_mincost_nonneg'),
    sa.CheckConstraint('von_haltepunkt_id <> nach_haltepunkt_id', name='ck_hpseg_from_to_diff'),
    sa.ForeignKeyConstraint(['halteplan_id'], ['halteplan.halteplan_id'], ),
    sa.ForeignKeyConstraint(['nach_haltepunkt_id'], ['haltepunkt.id'], ),
    sa.ForeignKeyConstraint(['von_haltepunkt_id'], ['haltepunkt.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('halteplan_id', 'position', name='uq_hpseg_pos')
    )
    with op.batch_alter_table('halteplan_segment', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_halteplan_segment_halteplan_id'), ['halteplan_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_halteplan_segment_nach_haltepunkt_id'), ['nach_haltepunkt_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_halteplan_segment_von_haltepunkt_id'), ['von_haltepunkt_id'], unique=False)

    op.create_table('fahrt_segment',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('fahrt_id', sa.Integer(), nullable=False),
    sa.Column('von_halt_id', sa.Integer(), nullable=False),
    sa.Column('nach_halt_id', sa.Integer(), nullable=False),
    sa.Column('position', sa.Integer(), nullable=False),
    sa.Column('final_price', sa.Float(), nullable=False),
    sa.Column('duration_min', sa.Integer(), nullable=False),
    sa.CheckConstraint('final_price >= 0', name='ck_fahrt_seg_price_nonneg'),
    sa.ForeignKeyConstraint(['fahrt_id'], ['fahrtdurchfuehrung.fahrt_id'], ),
    sa.ForeignKeyConstraint(['nach_halt_id'], ['fahrt_halt.id'], ),
    sa.ForeignKeyConstraint(['von_halt_id'], ['fahrt_halt.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('fahrt_id', 'position', name='uq_fahrt_seg_pos')
    )
    with op.batch_alter_table('fahrt_segment', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_fahrt_segment_fahrt_id'), ['fahrt_id'], unique=False)

    with op.batch_alter_table('fahrtdurchfuehrung', schema=None) as batch_op:
        batch_op.add_column(sa.Column('abfahrt_zeit', sa.DateTime(), nullable=False))
        batch_op.add_column(sa.Column('price_factor', sa.Float(), nullable=False))

    with op.batch_alter_table('halteplan', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_halteplan_strecke_id'), ['strecke_id'], unique=False)
        batch_op.create_foreign_key(None, 'strecke', ['strecke_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('halteplan', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_index(batch_op.f('ix_halteplan_strecke_id'))

    with op.batch_alter_table('fahrtdurchfuehrung', schema=None) as batch_op:
        batch_op.drop_column('price_factor')
        batch_op.drop_column('abfahrt_zeit')

    with op.batch_alter_table('fahrt_segment', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_fahrt_segment_fahrt_id'))

    op.drop_table('fahrt_segment')
    with op.batch_alter_table('halteplan_segment', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_halteplan_segment_von_haltepunkt_id'))
        batch_op.drop_index(batch_op.f('ix_halteplan_segment_nach_haltepunkt_id'))
        batch_op.drop_index(batch_op.f('ix_halteplan_segment_halteplan_id'))

    op.drop_table('halteplan_segment')
    with op.batch_alter_table('fahrt_halt', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_fahrt_halt_fahrt_id'))
        batch_op.drop_index(batch_op.f('ix_fahrt_halt_bahnhof_id'))

    op.drop_table('fahrt_halt')
    with op.batch_alter_table('haltepunkt', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_haltepunkt_halteplan_id'))
        batch_op.drop_index(batch_op.f('ix_haltepunkt_bahnhof_id'))

    op.drop_table('haltepunkt')
    # ### end Alembic commands ###
