"""add zug_wartung

Revision ID: 745aeb035496
Revises: e3d2596a5d2f
Create Date: 2026-01-07 17:32:22.506316

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '745aeb035496'
down_revision = 'e3d2596a5d2f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('zug_wartung',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('zug_id', sa.Integer(), nullable=False),
    sa.Column('external_wartungszeitid', sa.Integer(), nullable=False),
    sa.Column('von', sa.DateTime(), nullable=False),
    sa.Column('bis', sa.DateTime(), nullable=False),
    sa.CheckConstraint('bis > von', name='ck_zugwartung_bis_gt_von'),
    sa.ForeignKeyConstraint(['zug_id'], ['zug.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('zug_id', 'external_wartungszeitid', name='uq_zugwartung_zug_ext')
    )
    with op.batch_alter_table('zug_wartung', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_zug_wartung_external_wartungszeitid'), ['external_wartungszeitid'], unique=False)
        batch_op.create_index(batch_op.f('ix_zug_wartung_zug_id'), ['zug_id'], unique=False)

    with op.batch_alter_table('zug', schema=None) as batch_op:
        batch_op.drop_column('in_wartung')
        batch_op.drop_column('wartung_bis')
        batch_op.drop_column('wartungszeitid')
        batch_op.drop_column('wartung_von')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('zug', schema=None) as batch_op:
        batch_op.add_column(sa.Column('wartung_von', sa.DATETIME(), nullable=True))
        batch_op.add_column(sa.Column('wartungszeitid', sa.INTEGER(), nullable=True))
        batch_op.add_column(sa.Column('wartung_bis', sa.DATETIME(), nullable=True))
        batch_op.add_column(sa.Column('in_wartung', sa.BOOLEAN(), nullable=False))

    with op.batch_alter_table('zug_wartung', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_zug_wartung_zug_id'))
        batch_op.drop_index(batch_op.f('ix_zug_wartung_external_wartungszeitid'))

    op.drop_table('zug_wartung')
    # ### end Alembic commands ###
