"""trying again

Revision ID: ab95c3471da3
Revises: 5064cbb6c2b4
Create Date: 2025-12-17 20:58:41.485730

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ab95c3471da3'
down_revision = '5064cbb6c2b4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###

    with op.batch_alter_table('halteplan', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_halteplan_strecke_id'), ['strecke_id'], unique=False)
        batch_op.create_foreign_key(
            "fk_halteplan_strecke_id_strecke",
            "strecke",
            ["strecke_id"],
            ["id"]
        )

    # ### end Alembic commands ###


def downgrade():
    with op.batch_alter_table('halteplan', schema=None) as batch_op:
        batch_op.drop_constraint("fk_halteplan_strecke_id_strecke", type_='foreignkey')
        batch_op.drop_index(batch_op.f('ix_halteplan_strecke_id'))



    # ### end Alembic commands ###
