"""initial schema

Revision ID: cd8c44890353
Revises: 
Create Date: 2025-11-25 22:52:26.850655

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cd8c44890353'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('halteplan',
    sa.Column('halteplan_id', sa.Integer(), nullable=False),
    sa.Column('bezeichnung', sa.String(length=128), nullable=False),
    sa.Column('strecke_id', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('halteplan_id')
    )
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=64), nullable=False),
    sa.Column('password_hash', sa.String(length=256), nullable=True),
    sa.Column('role', sa.Enum('ADMIN', 'MITARBEITER', name='role'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_user_username'), ['username'], unique=True)

    op.create_table('fahrtdurchfuehrung',
    sa.Column('fahrt_id', sa.Integer(), nullable=False),
    sa.Column('halteplan_id', sa.Integer(), nullable=False),
    sa.Column('zug_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('PLANMAESSIG', 'VERSPAETET', 'AUSGEFALLEN', name='fahrtdurchfuehrungstatus'), nullable=False),
    sa.Column('verspaetung_min', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['halteplan_id'], ['halteplan.halteplan_id'], ),
    sa.PrimaryKeyConstraint('fahrt_id')
    )
    op.create_table('mitarbeiter',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id')
    )
    op.create_table('dienstzuweisung',
    sa.Column('dienst_id', sa.Integer(), nullable=False),
    sa.Column('fahrt_id', sa.Integer(), nullable=False),
    sa.Column('mitarbeiter_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['fahrt_id'], ['fahrtdurchfuehrung.fahrt_id'], ),
    sa.ForeignKeyConstraint(['mitarbeiter_id'], ['mitarbeiter.id'], ),
    sa.PrimaryKeyConstraint('dienst_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('dienstzuweisung')
    op.drop_table('mitarbeiter')
    op.drop_table('fahrtdurchfuehrung')
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_user_username'))

    op.drop_table('user')
    op.drop_table('halteplan')
    # ### end Alembic commands ###
