"""add zug table and fk to fahrtdurchfuehrung

Revision ID: e3d2596a5d2f
Revises: 491fc61ff84b
Create Date: 2026-01-07 17:05:06.324747

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e3d2596a5d2f'
down_revision = '491fc61ff84b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('fahrtdurchfuehrung', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_fahrtdurchfuehrung_zug_id'), ['zug_id'], unique=False)
        batch_op.create_foreign_key("fk_fahrtdurchfuehrung_zug_id_zug", 'zug', ['zug_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('fahrtdurchfuehrung', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_index(batch_op.f('ix_fahrtdurchfuehrung_zug_id'))

    # ### end Alembic commands ###
